import type { Metadata } from "next";
import { ArrowDownRight, ArrowUpRight } from "lucide-react";
import { PageHeader } from "@/components/layout/page-header";
import { Select } from "@/components/ui/select";
import { compareBuilds } from "@/lib/api/telemetry";

export const metadata: Metadata = { title: "Compare builds" };

export default async function ComparePage() {
  const { metrics, sample } = await compareBuilds("1.7.9", "1.8.0");
  return <><PageHeader title="Build match-up" description="Compare release behavior on one scale and expose regressions before they disappear into averages." actions={<span className="text-xs font-semibold text-info">{sample ? "Sample workspace data" : "Live workspace data"}</span>} /><div className="mb-5 grid gap-3 rounded-panel bg-surface p-4 sm:grid-cols-[1fr_auto_1fr] sm:items-end"><label className="grid gap-1.5"><span className="text-xs font-semibold text-muted">Baseline build</span><Select defaultValue="1.7.9" className="w-full"><option>1.7.9</option><option>1.7.8</option></Select></label><span className="pb-2 text-center text-xs font-bold text-faint">VERSUS</span><label className="grid gap-1.5"><span className="text-xs font-semibold text-muted">Candidate build</span><Select defaultValue="1.8.0" className="w-full"><option>1.8.0</option><option>1.8.1-rc</option></Select></label></div><section className="overflow-x-auto rounded-panel bg-surface"><div className="min-w-[42rem]"><header className="grid grid-cols-[minmax(10rem,1fr)_8rem_8rem_7rem] border-b border-line bg-surface-sunken px-5 py-3 text-xs font-bold tracking-wide text-muted"><span>Metric</span><span>1.7.9</span><span>1.8.0</span><span>Change</span></header>{metrics.map((metric) => { const regressed = metric.favorable === "down" ? metric.delta > 0 : metric.delta < 0; const Icon = metric.delta > 0 ? ArrowUpRight : ArrowDownRight; return <div key={metric.metric} className="grid grid-cols-[minmax(10rem,1fr)_8rem_8rem_7rem] items-center border-b border-line px-5 py-5 last:border-0"><div><h2 className="font-semibold text-ink">{metric.metric}</h2><p className="mt-1 text-xs text-muted">Candidate vs baseline</p></div><span className="font-mono text-lg text-muted">{metric.buildA}{metric.unit}</span><span className={`font-mono text-lg font-bold ${regressed ? "text-critical" : "text-low"}`}>{metric.buildB}{metric.unit}</span><span className={`inline-flex items-center gap-1 font-mono text-sm font-bold ${regressed ? "text-critical" : "text-low"}`}><Icon size={15} />{metric.delta > 0 ? "+" : ""}{metric.delta}%</span></div>; })}</div></section><div className="mt-5 grid gap-5 lg:grid-cols-2"><section className="rounded-panel bg-critical-surface p-5"><h2 className="font-bold text-critical">Release risk increased</h2><p className="mt-2 text-sm leading-6 text-ink">Build 1.8.0 raises boss failure and quit rates while reducing completion. The change aligns with the top feedback cluster at 92% confidence.</p></section><section className="rounded-panel bg-surface p-5"><h2 className="font-bold text-ink">Affected segment</h2><p className="mt-2 text-sm leading-6 text-muted">New Android players show the largest regression: failure rate <span className="font-mono text-critical">+91%</span> and completion <span className="font-mono text-critical">-31%</span>.</p></section></div></>;
}
