import type { Metadata } from "next";
import { TopicCluster } from "@/components/feedback/topic-cluster";
import { PageHeader } from "@/components/layout/page-header";
import { Select } from "@/components/ui/select";
import { getTopics } from "@/lib/api/feedback";

export const metadata: Metadata = { title: "Feedback" };

export default async function FeedbackPage() {
  const { topics, sample } = await getTopics(); const max = Math.max(...topics.map((topic) => topic.mentions));
  return <><PageHeader title="Feedback topic finder" description="Cluster player language by theme, sentiment, source, and build without losing the underlying reports." actions={<span className="text-xs font-semibold text-info">{sample ? "Sample workspace data" : "Live workspace data"}</span>} /><div className="mb-5 flex flex-wrap gap-3 rounded-panel bg-surface p-4"><label className="grid gap-1.5"><span className="text-xs font-semibold text-muted">Source</span><Select defaultValue="ALL"><option>ALL</option><option>STEAM</option><option>DISCORD</option><option>REDDIT</option><option>SUPPORT</option></Select></label><label className="grid gap-1.5"><span className="text-xs font-semibold text-muted">Sentiment</span><Select defaultValue="NEGATIVE"><option>ALL</option><option>NEGATIVE</option><option>MIXED</option><option>POSITIVE</option></Select></label><label className="grid gap-1.5"><span className="text-xs font-semibold text-muted">Build</span><Select defaultValue="1.8.0"><option>1.8.0</option><option>1.7.9</option></Select></label></div><div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_20rem]"><section className="overflow-hidden rounded-panel bg-surface"><header className="border-b border-line px-5 py-4"><h2 className="font-bold text-ink">Topic clusters</h2><p className="mt-1 text-sm text-muted">Share of conversation with trend and source coverage.</p></header>{topics.map((topic) => <TopicCluster key={topic.id} topic={topic} max={max} />)}</section><aside className="rounded-panel bg-surface p-5"><h2 className="font-bold text-ink">Sentiment mix</h2><div className="mt-5 space-y-4"><Sentiment label="Negative" value="68%" change="+19%" tone="bg-critical" /><Sentiment label="Mixed" value="21%" change="-4%" tone="bg-medium" /><Sentiment label="Positive" value="11%" change="-15%" tone="bg-low" /></div><p className="mt-6 border-t border-line pt-4 text-sm leading-6 text-muted">Boss shield timing accounts for 42% of the negative growth after build 1.8.0.</p></aside></div></>;
}

function Sentiment({ label, value, change, tone }: { label: string; value: string; change: string; tone: string }) { return <div><div className="flex justify-between text-sm"><span className="font-semibold text-ink">{label}</span><span className="font-mono text-muted">{value} <span className={label === "Negative" ? "text-critical" : "text-low"}>{change}</span></span></div><div className="mt-2 h-2 bg-surface-sunken"><div className={`h-2 ${tone}`} style={{ width: value }} /></div></div>; }
