import type { Metadata } from "next";
import { FunnelChart } from "@/components/charts/funnel-chart";
import { TrendChart } from "@/components/charts/trend-chart";
import { PageHeader } from "@/components/layout/page-header";
import { Select } from "@/components/ui/select";
import { getTelemetry } from "@/lib/api/telemetry";
import { signed } from "@/lib/utils/format";

export const metadata: Metadata = { title: "Telemetry" };

export default async function TelemetryPage() {
  const { events, sample } = await getTelemetry();
  return <><PageHeader title="Behavior signal monitor" description="Track failure, retry, quit, and completion behavior by event and build." actions={<span className="text-xs font-semibold text-info">{sample ? "Sample workspace data" : "Live workspace data"}</span>} /><div className="mb-5 flex flex-wrap gap-3 rounded-panel bg-surface p-4"><label className="grid gap-1.5"><span className="text-xs font-semibold text-muted">Event</span><Select defaultValue="boss_failed"><option>boss_failed</option><option>session_quit</option><option>boss_retry</option></Select></label><label className="grid gap-1.5"><span className="text-xs font-semibold text-muted">Build</span><Select defaultValue="1.8.0"><option>1.8.0</option><option>1.7.9</option></Select></label></div><div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_22rem]"><section className="rounded-panel bg-surface p-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="font-bold text-ink">boss_failed event trend</h2><p className="mt-1 text-sm text-muted">Current failure rate <span className="font-mono text-critical">{events[0].current}{events[0].unit} · {signed(events[0].change)}</span></p></div><span className="font-mono text-xs text-high">BUILD CUT · 1.8.0</span></div><div className="mt-4 rounded-control bg-surface-sunken p-2"><TrendChart data={events[0].points} /></div></section><section className="rounded-panel bg-surface p-5"><h2 className="font-bold text-ink">Boss encounter funnel</h2><p className="mt-1 text-sm text-muted">Build 1.8.0 versus prior 7 days.</p><div className="mt-6"><FunnelChart stages={[{ label: "Encounter started", value: 12480, change: 8 }, { label: "Shield broken", value: 8736, change: -12 }, { label: "Final phase", value: 5614, change: -21 }, { label: "Boss defeated", value: 3210, change: -34 }]} /></div></section></div><section className="mt-5 overflow-hidden rounded-panel bg-surface"><header className="border-b border-line px-5 py-4"><h2 className="font-bold text-ink">Event watchlist</h2></header><div className="grid divide-y divide-line md:grid-cols-3 md:divide-x md:divide-y-0">{events.map((event) => <div key={event.event} className="p-5"><p className="font-mono text-xs font-semibold text-muted">{event.event}</p><p className="mt-3 font-mono text-3xl font-bold text-ink">{event.current}{event.unit} <span className="text-sm text-critical">{signed(event.change)}</span></p><p className="mt-2 text-sm text-muted">vs prior 7 days</p></div>)}</div></section></>;
}
